=== MrXFei/BMGenTestCase/BMGenTool/bin/Debug/compiler/CompilerLEUV6001/parser/LEU.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- LEU compiler input file DTD  -->
<!-- $Id: LEU.dtd,v 1.1.2.2 2007/08/29 09:50:44 sebilleau Exp $-->
<!ELEMENT Application_Category (#PCDATA)>
<!ELEMENT Aspect (Mask, Telegram)>

<!ELEMENT Channel (#PCDATA)>
<!ELEMENT DATAVER (DATAVER_A, DATAVER_B, NUM_DATAVER, FSFB2_SRC_ADD)>
<!ATTLIST DATAVER
	id CDATA #REQUIRED
>
<!ELEMENT DATAVER_A (#PCDATA)>
<!ELEMENT DATAVER_B (#PCDATA)>
<!ELEMENT DELTA_N_MAX (#PCDATA)>
<!ELEMENT Default_telegram (#PCDATA)>
<!ELEMENT Encoder (TE_NUMBER, TEMPO_T1, TEMPO_T2, SYNC_MASTER_BOARD, NETWORK_GID, FIP_ENCODER_PN?, FIP_SUB_NETWORK_ADD?, SYSCKW_A, SYSCKW_B, SL_CHANGEOVER?)>
<!ATTLIST Encoder
	mode (Signalling | Transparent | Gateway) #REQUIRED
>
<!ELEMENT FIP_ENCODER_PN (#PCDATA)>
<!ELEMENT FIP_SUB_NETWORK_ADD (#PCDATA)>
<!ELEMENT FSFB2_Node_Cycle (#PCDATA)>
<!ELEMENT FSFB2_SRC_ADD (#PCDATA)>
<!ELEMENT FSFB2_Subnet_Ad (#PCDATA)>
<!ELEMENT GATEWAY (GATEWAY_IP_ADDRESS, GATEWAY_MAC_ADDRESS, GATEWAY_IP_PORT, IXL_IP_ADDRESS, IXL_IP_PORT, IXL_FSFB2_PARAMS+)>
<!ELEMENT GATEWAY_IP_ADDRESS (#PCDATA)>
<!ELEMENT GATEWAY_IP_PORT (#PCDATA)>
<!ELEMENT GATEWAY_MAC_ADDRESS (#PCDATA)>
<!ELEMENT GID (#PCDATA)>
<!ELEMENT INPUT_BOARD (SLOT, GID, TYPE)>
<!ATTLIST INPUT_BOARD
	id CDATA #REQUIRED
>
<!ELEMENT IXL_FSFB2_ADD (#PCDATA)>
<!ELEMENT IXL_FSFB2_PARAMS (IXL_FSFB2_ADD, IXL_VFIP_ADD)>
<!ELEMENT IXL_IP_ADDRESS (#PCDATA)>
<!ELEMENT IXL_IP_PORT (#PCDATA)>
<!ELEMENT IXL_VFIP_ADD (#PCDATA)>
<!ELEMENT Input (Channel, Number)>


<!ELEMENT LEU (INPUT_BOARD*, OUTPUT_BOARD?, SLIB_BOARD?, SLEB_BOARD?, Output_balise*, Encoder, Network, GATEWAY?, POSIXDATE_TPC, VERID_TPC, POSIXDATE_TSE, VERID_TSE, POSIXDATE_TE?, VERID_TE?)>
<!ATTLIST LEU
	name CDATA #IMPLIED
>
<!ELEMENT LIFETIME_MAX (#PCDATA)>
<!ELEMENT Mask (#PCDATA)>
<!ELEMENT Max_SSR_Retry (#PCDATA)>
<!ELEMENT Max_Tc_Err (#PCDATA)>
<!ELEMENT NETWORK_GID (#PCDATA)>
<!ELEMENT NUM_DATAVER (#PCDATA)>
<!ELEMENT N_BSD_TO_SSR (#PCDATA)>
<!ELEMENT Network (Transmit_Channel, Receive_Channel*)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT OUTPUT_BOARD (SLOT, GID, TYPE, TEL_number)>
<!ELEMENT Output_balise (Input*, Aspect*, Default_telegram)>
<!ATTLIST Output_balise
	id CDATA #REQUIRED
	telegram (SHORT | LONG) #REQUIRED
>
<!ELEMENT POSIXDATE_TE (#PCDATA)>
<!ELEMENT POSIXDATE_TPC (#PCDATA)>
<!ELEMENT POSIXDATE_TSE (#PCDATA)>
<!ELEMENT Receive_Channel (VFIP_ADD?, FSFB2_Node_Cycle, N_BSD_TO_SSR, FSFB2_SRC_ADD, Max_Tc_Err, Max_SSR_Retry, SID_A, SID_B, SINIT_A, SINIT_B, LIFETIME_MAX, DELTA_N_MAX, DATAVER_A, DATAVER_B, NUM_DATAVER)>
<!ATTLIST Receive_Channel
	id CDATA #REQUIRED
>
<!ELEMENT SID_A (#PCDATA)>
<!ELEMENT SID_B (#PCDATA)>
<!ELEMENT SINIT_A (#PCDATA)>
<!ELEMENT SINIT_B (#PCDATA)>
<!ELEMENT SLEB_BOARD (SLOT, GID, TYPE, SLEB_LINK_SPEED)>
<!ELEMENT SLEB_LINK_SPEED (#PCDATA)>
<!ELEMENT SLIB_BOARD (SLOT, GID, TYPE, SLIB_LINK)>
<!ELEMENT SLIB_LINK (#PCDATA)>
<!ATTLIST SLIB_LINK
	id CDATA #REQUIRED
>
<!ELEMENT SLOT (#PCDATA)>
<!ELEMENT SL_CHANGEOVER (#PCDATA)>
<!ELEMENT SYNC_MASTER_BOARD (#PCDATA)>
<!ELEMENT SYSCKW_A (#PCDATA)>
<!ELEMENT SYSCKW_B (#PCDATA)>
<!ELEMENT TEL_number (#PCDATA)>
<!ELEMENT TEMPO_T1 (#PCDATA)>
<!ELEMENT TEMPO_T2 (#PCDATA)>
<!ELEMENT TE_NUMBER (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT Telegram (#PCDATA)>
<!ELEMENT Transmit_Channel (VFIP_ADD?, Application_Category, FSFB2_Subnet_Ad, FSFB2_SRC_ADD, SID_A, SID_B, SINIT_A, SINIT_B, DATAVER*)>
<!ELEMENT VERID_TE (#PCDATA)>
<!ELEMENT VERID_TPC (#PCDATA)>
<!ELEMENT VERID_TSE (#PCDATA)>
<!ELEMENT VFIP_ADD (#PCDATA)>

=== MrXFei/BMGenTestCase/BMGenTool/bin/Debug/compiler/CompilerLEUV6001/parser/input.xml
<?xml version='1.0' standalone='no'?>
<!-- LEU_Generic data COMPILER  file: C:\Files\workspacesC\BMGen\SourceCode\BMGenTool\bin\Debug\output\LEUBinary\E7D\E7D.xml processed on Mon Jun 15 09:40:06 2020 -->
<!DOCTYPE World SYSTEM "LEU.dtd">
<!--Data of generation: Bcode_iTRNV-BMGenTool2_V1.0.2_Build_20200409_debug-->
<LEU name="E7D">
  <INPUT_BOARD id="1">
    <SLOT>15</SLOT>
    <GID>1AE7490209CA4B55</GID>
    <TYPE>04</TYPE>
  </INPUT_BOARD>
  <OUTPUT_BOARD>
    <SLOT>19</SLOT>
    <GID>28554C0C1BABBBA8</GID>
    <TYPE>01</TYPE>
    <TEL_number>7F</TEL_number>
  </OUTPUT_BOARD>
  <Output_balise id="1" telegram="LONG">
    <Input>
      <Channel>00</Channel>
      <Number>01</Number>
    </Input>
    <Aspect>
      <Mask>0XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Mask>
      <Telegram>90 00 7F 80 61 3C 0B 10 18 32 80 00 4B 10 3E 32 C0 00 08 00 00 00 00 96 00 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Telegram>
    </Aspect>
    <Aspect>
      <Mask>1XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Mask>
      <Telegram>90 00 7F 80 61 3C 0B 10 18 32 80 00 4B 10 3E 32 C0 00 10 00 00 01 25 C5 00 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Telegram>
    </Aspect>
    <Default_telegram>90 00 00 00 61 3C 0B 10 18 32 80 00 4B 10 3E 32 C0 00 08 00 00 80 00 00 00 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Default_telegram>
  </Output_balise>
  <Output_balise id="2" telegram="LONG">
    <Input>
      <Channel>00</Channel>
      <Number>02</Number>
    </Input>
    <Aspect>
      <Mask>0XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Mask>
      <Telegram>90 00 7F 80 61 3F 0B 10 18 32 80 00 4B 10 3E 32 C0 00 08 00 00 00 00 96 00 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Telegram>
    </Aspect>
    <Aspect>
      <Mask>1XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</Mask>
      <Telegram>90 00 7F 80 61 3F 0B 10 18 32 80 00 4B 10 3E 32 C0 00 10 00 00 00 F0 5A C0 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Telegram>
    </Aspect>
    <Default_telegram>90 00 00 00 61 3F 0B 10 18 32 80 00 4B 10 3E 32 C0 00 08 00 00 80 00 00 00 00 00 03 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FC</Default_telegram>
  </Output_balise>
  <Encoder mode="Signalling">
    <TE_NUMBER>01</TE_NUMBER>
    <TEMPO_T1>10</TEMPO_T1>
    <TEMPO_T2>05</TEMPO_T2>
    <SYNC_MASTER_BOARD>19</SYNC_MASTER_BOARD>
    <NETWORK_GID>3B23BA87765598C1</NETWORK_GID>
    <FIP_ENCODER_PN>02</FIP_ENCODER_PN>
    <FIP_SUB_NETWORK_ADD>00</FIP_SUB_NETWORK_ADD>
    <SYSCKW_A>AE390B5A</SYSCKW_A>
    <SYSCKW_B>C103589C</SYSCKW_B>
    <SL_CHANGEOVER>03</SL_CHANGEOVER>
  </Encoder>
  <Network>
    <Transmit_Channel>
      <VFIP_ADD>01</VFIP_ADD>
      <Application_Category>01</Application_Category>
      <FSFB2_Subnet_Ad>FFFF</FSFB2_Subnet_Ad>
      <FSFB2_SRC_ADD>0006</FSFB2_SRC_ADD>
      <SID_A>5B26603C</SID_A>
      <SID_B>64C54B3E</SID_B>
      <SINIT_A>26AA6538</SINIT_A>
      <SINIT_B>5C82653A</SINIT_B>
      <DATAVER id="1">
        <DATAVER_A>6DB31504</DATAVER_A>
        <DATAVER_B>37540506</DATAVER_B>
        <NUM_DATAVER>01</NUM_DATAVER>
        <FSFB2_SRC_ADD>00FF</FSFB2_SRC_ADD>
      </DATAVER>
    </Transmit_Channel>
  </Network>
  <POSIXDATE_TPC>45A5D260</POSIXDATE_TPC>
  <VERID_TPC>1222222</VERID_TPC>
  <POSIXDATE_TSE>45A5D260</POSIXDATE_TSE>
  <VERID_TSE>1444444</VERID_TSE>
  <POSIXDATE_TE>45A5D260</POSIXDATE_TE>
  <VERID_TE>1AAAAAA</VERID_TE>
</LEU>
